name: Attu dev release

on:
  pull_request_target:
    branches: [main]
    types: [closed]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        platform:
          - linux/amd64
          - linux/arm64      
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: zilliz/attu:dev
          build-args: VERSION=dev
          push: true
